### ISSUE TITLE
Text Size

### ISSUE THREAD

**Issue by Annis-Monadjem** [egoist/devdocs-app#24]
Thanks for making and sharing `Devdoc`!
I have difficulty reading for long small text size of articles/reference pages and unfortunately, `Devdoc` comes with very small text size.
**Please make text size adjustable so that it can be customized by user.**

**Comment by egoist** [comment]
Checkout `v0.3.0` release: https://github.com/egoist/devdocs-app/releases/tag/v0.3.0

You can add following CSS to your custom CSS file:

```css
._list-item, ._content {
  font-size: 1rem !important;
}
```
